# Generated by Django 6.0.5 on 2026-05-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(db_column='ID_agendamento', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(max_length=45)),
                ('valor_total', models.FloatField()),
                ('animal', models.ForeignKey(db_column='ANIMAL_ID_animal', on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'AGENDAMENTO',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(db_column='AGENDAMENTO_ID_agendamento', on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
                ('servico', models.ForeignKey(db_column='SERVICO_ID_servico', on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
            options={
                'verbose_name': 'Agendamento Serviço',
                'verbose_name_plural': 'Agendamentos Serviços',
                'db_table': 'AGENDAMENTO_SERVICO',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(through='agendamento.AgendamentoServico', to='servico.servico'),
        ),
    ]
