# Generated by Django 6.0.5 on 2026-05-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='animal',
            field=models.ForeignKey(db_column='ANIMAL_ID_animal', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
