# Generated by Django 6.0.5 on 2026-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_cliente', primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=75)),
                ('cpf_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone_cliente', models.CharField(max_length=13)),
                ('endereco_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=45)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
    ]
