# Generated by Django 6.0.5 on 2026-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(db_column='ID_servico', primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=45)),
                ('descricao_servico', models.CharField(max_length=45)),
                ('preco_servico', models.FloatField()),
                ('duracao_servico', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'SERVICO',
            },
        ),
    ]
