# Generated by Django 6.0.5 on 2026-05-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(db_column='ID_animal', primary_key=True, serialize=False)),
                ('nome_pet', models.CharField(db_column='Nome_pet', max_length=45)),
                ('raca', models.CharField(db_column='Raca', max_length=45)),
                ('especie', models.CharField(db_column='Especie', max_length=45)),
                ('data_nascimento', models.DateField(db_column='Data_nascimento')),
                ('peso', models.FloatField(db_column='Peso')),
                ('imagem', models.CharField(blank=True, db_column='Foto_perfil', max_length=45, null=True)),
                ('observacoes', models.CharField(blank=True, db_column='Observacoes', max_length=255, null=True)),
                ('cliente', models.ForeignKey(db_column='CLIENTE_ID_cliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'ANIMAL',
            },
        ),
    ]
